version: 2.1

orbs:
  python: circleci/python@2

jobs:
  test-python:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Run tests
          command: pytest test_mail_logic.py --cov=./ || ((($? == 5)) && echo 'Did not find any tests to run.')
      - store_test_results:
          path: junit.xml

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: ''

workflows:
  build-and-test:
    jobs:
      - test-python
      # - deploy:
      #     requires:
      #       - test-python